

alter table  tblLenhXuatE5 add BatchNum nvarchar(100), NgayVaoKho date, SMO_ID nvarchar(300), SoBienBan nvarchar(300), NgayLapBienBan nvarchar(200), CrSysDate datetime
alter table  tblLenhXuat_HangHoaE5 add BatchNum nvarchar(100)
alter table  tblLenhXuatChiTietE5 add BatchNum nvarchar(100)

--INSERT INTO [dbo].[tblLenhXuatE5]([MaLenh],[NgayXuat],[SoLenh],[MaDonVi],[MaNguon],[MaKho],[MaVanChuyen] ,[MaPhuongTien],[NguoiVanChuyen],[MaPhuongThucBan],[MaPhuongThucXuat],[MaKhachHang],[LoaiPhieu] ,[Niem],[LuongGiamDinh] ,[NhietDoTaiTau],[GhiChu],[NgayHieuLuc],[Status],[Number],[Createby] ,[UpdatedBy],[CreateDate],[UpdateDate],[SoLenhSAP],[Client],[HTTG],[Approved] ,[User_Approve],[Date_Approve] ,[EditApprove],[NhaCungCap],[AppDesc],[AppN30],[AppN30Date],[AppN30User],[QCI_KG],[QCI_NhietDo] ,[Slog],[NgayHetHieuLuc],[NgayTichKe],[STO],[NguoiDaiDien],[DonViCungCapVanTai],[UserTichKe] ,[DiemTraHang],[Tax],[PaymentMethod],[Term],[MaKhoNhap],[SoHopDong],[NgayHopDong],[TyGia] ,[SoTKHQNhap],[SoTKHQXuat],[SelfShipping],[PriceGroup],[Inco1],[Inco2],[SoPXK],[NgayPXK] ,[MaTuyenDuong],[XuatHangGui],[So_TKTN],[So_TKTX],[Ngay_TKTX],[PTXuat_ID],[DischargePoint] ,[DesDischargePoint],[BSART],[BWART],[VTWEG],[TenKhoNhap],[Xitec_Option],[SoLenhGoc],[Dem],[PTIEN] ,[SCHUYEN],[NgayVaoKho],[SMO_ID],[CardNum] 
--,[CardData],[MaTraCuu],[TongSoNiem],[SoBienBanMau] ,[DO1_SoLenh],[DO1_MaKhach],[SoBienBan],[NgayLapBienBan],[SOType],[PrcingDate],[POType],[FromSoLenh] ,[PriceGroupDO1],[LXLoai],[LXPhieu],[SO_POType],[Prcing],[DOCT],[HDChuyen],[BatchNum],[DO1_MaNguon] ,[CrSysDate],[PriceSynDate],[NOTE_LX],[SO_CHUYEN],[LOAI_KH],[NOTE_SMO],[NhomBeXuat] ,[NhomBeAPP],[NhomBeAPPU],[NhomBeAPPD],[ThongTinTDH],[trangthai],[TK_SynDate],[R_KWMENG2]) SELECT    [MaLenh],[NgayXuat],[SoLenh],[MaDonVi],[MaNguon],[MaKho],[MaVanChuyen] ,[MaPhuongTien],[NguoiVanChuyen],[MaPhuongThucBan],[MaPhuongThucXuat],[MaKhachHang],[LoaiPhieu] ,[Niem],[LuongGiamDinh] ,[NhietDoTaiTau],[GhiChu],[NgayHieuLuc],[Status],[Number],1 as [Createby] ,1 as  [UpdatedBy], getdate() as [CreateDate], getdate() as [UpdateDate],[SoLenhSAP],[Client],[HTTG],[Approved] ,[User_Approve],[Date_Approve] ,[EditApprove],[NhaCungCap],[AppDesc],[AppN30],[AppN30Date],[AppN30User],[QCI_KG],[QCI_NhietDo] ,[Slog],[NgayHetHieuLuc],[NgayTichKe],[STO],[NguoiDaiDien],[DonViCungCapVanTai],[UserTichKe]
--,[DiemTraHang],[Tax],[PaymentMethod],[Term],[MaKhoNhap],[SoHopDong],[NgayHopDong],[TyGia] ,[SoTKHQNhap],[SoTKHQXuat],[SelfShipping],[PriceGroup],[Inco1],[Inco2],[SoPXK],[NgayPXK] ,[MaTuyenDuong],[XuatHangGui],[So_TKTN],[So_TKTX],[Ngay_TKTX],[PTXuat_ID],[DischargePoint] ,[DesDischargePoint],[BSART],[BWART],[VTWEG],[TenKhoNhap],[Xitec_Option],[SoLenhGoc],[Dem],[PTIEN] ,[SCHUYEN],[NgayVaoKho],[SMO_ID],[CardNum] ,[CardData],[MaTraCuu],[TongSoNiem],[SoBienBanMau] ,[DO1_SoLenh],[DO1_MaKhach],[SoBienBan],[NgayLapBienBan],[SOType],[PrcingDate],[POType],[FromSoLenh] ,[PriceGroupDO1],[LXLoai],[LXPhieu],[SO_POType],[Prcing],[DOCT],[HDChuyen],[BatchNum],[DO1_MaNguon] ,[CrSysDate],[PriceSynDate],[NOTE_LX],[SO_CHUYEN],[LOAI_KH],[NOTE_SMO],[NhomBeXuat] ,[NhomBeAPP],[NhomBeAPPU],[NhomBeAPPD],[ThongTinTDH],[trangthai],[TK_SynDate],[R_KWMENG2]  from tblLenhXuatE5_THN where solenh ='2000014708' 

