'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System


<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0"),  _
 Serializable(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.ComponentModel.ToolboxItem(true),  _
 System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema"),  _
 System.Xml.Serialization.XmlRootAttribute("RpDataset"),  _
 System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")>  _
Partial Public Class RpDataset
    Inherits System.Data.DataSet
    
    Private tablewwTrans As wwTransDataTable
    
    Private _schemaSerializationMode As System.Data.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Sub New()
        MyBase.New
        Me.BeginInit
        Me.InitClass
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler MyBase.Relations.CollectionChanged, schemaChangedHandler
        Me.EndInit
    End Sub
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Sub New(ByVal info As System.Runtime.Serialization.SerializationInfo, ByVal context As System.Runtime.Serialization.StreamingContext)
        MyBase.New(info, context, false)
        If (Me.IsBinarySerialized(info, context) = true) Then
            Me.InitVars(false)
            Dim schemaChangedHandler1 As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
            AddHandler Me.Tables.CollectionChanged, schemaChangedHandler1
            AddHandler Me.Relations.CollectionChanged, schemaChangedHandler1
            Return
        End If
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(String)),String)
        If (Me.DetermineSchemaSerializationMode(info, context) = System.Data.SchemaSerializationMode.IncludeSchema) Then
            Dim ds As System.Data.DataSet = New System.Data.DataSet
            ds.ReadXmlSchema(New System.Xml.XmlTextReader(New System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("wwTrans")) Is Nothing) Then
                MyBase.Tables.Add(New wwTransDataTable(ds.Tables("wwTrans")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXmlSchema(New System.Xml.XmlTextReader(New System.IO.StringReader(strSchema)))
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property wwTrans() As wwTransDataTable
        Get
            Return Me.tablewwTrans
        End Get
    End Property
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     System.ComponentModel.BrowsableAttribute(true),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Visible)>  _
    Public Overrides Property SchemaSerializationMode() As System.Data.SchemaSerializationMode
        Get
            Return Me._schemaSerializationMode
        End Get
        Set
            Me._schemaSerializationMode = value
        End Set
    End Property
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Tables() As System.Data.DataTableCollection
        Get
            Return MyBase.Tables
        End Get
    End Property
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Relations() As System.Data.DataRelationCollection
        Get
            Return MyBase.Relations
        End Get
    End Property
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Sub InitializeDerivedDataSet()
        Me.BeginInit
        Me.InitClass
        Me.EndInit
    End Sub
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Overrides Function Clone() As System.Data.DataSet
        Dim cln As RpDataset = CType(MyBase.Clone,RpDataset)
        cln.InitVars
        cln.SchemaSerializationMode = Me.SchemaSerializationMode
        Return cln
    End Function
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As System.Xml.XmlReader)
        If (Me.DetermineSchemaSerializationMode(reader) = System.Data.SchemaSerializationMode.IncludeSchema) Then
            Me.Reset
            Dim ds As System.Data.DataSet = New System.Data.DataSet
            ds.ReadXml(reader)
            If (Not (ds.Tables("wwTrans")) Is Nothing) Then
                MyBase.Tables.Add(New wwTransDataTable(ds.Tables("wwTrans")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXml(reader)
            Me.InitVars
        End If
    End Sub
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function GetSchemaSerializable() As System.Xml.Schema.XmlSchema
        Dim stream As System.IO.MemoryStream = New System.IO.MemoryStream
        Me.WriteXmlSchema(New System.Xml.XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return System.Xml.Schema.XmlSchema.Read(New System.Xml.XmlTextReader(stream), Nothing)
    End Function
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Friend Overloads Sub InitVars()
        Me.InitVars(true)
    End Sub
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Friend Overloads Sub InitVars(ByVal initTable As Boolean)
        Me.tablewwTrans = CType(MyBase.Tables("wwTrans"),wwTransDataTable)
        If (initTable = true) Then
            If (Not (Me.tablewwTrans) Is Nothing) Then
                Me.tablewwTrans.InitVars
            End If
        End If
    End Sub
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Sub InitClass()
        Me.DataSetName = "RpDataset"
        Me.Prefix = ""
        Me.Namespace = "http://tempuri.org/RpDataset.xsd"
        Me.EnforceConstraints = true
        Me.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema
        Me.tablewwTrans = New wwTransDataTable
        MyBase.Tables.Add(Me.tablewwTrans)
    End Sub
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Function ShouldSerializewwTrans() As Boolean
        Return false
    End Function
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Shared Function GetTypedDataSetSchema(ByVal xs As System.Xml.Schema.XmlSchemaSet) As System.Xml.Schema.XmlSchemaComplexType
        Dim ds As RpDataset = New RpDataset
        Dim type As System.Xml.Schema.XmlSchemaComplexType = New System.Xml.Schema.XmlSchemaComplexType
        Dim sequence As System.Xml.Schema.XmlSchemaSequence = New System.Xml.Schema.XmlSchemaSequence
        xs.Add(ds.GetSchemaSerializable)
        Dim any As System.Xml.Schema.XmlSchemaAny = New System.Xml.Schema.XmlSchemaAny
        any.Namespace = ds.Namespace
        sequence.Items.Add(any)
        type.Particle = sequence
        Return type
    End Function
    
    Public Delegate Sub wwTransRowChangeEventHandler(ByVal sender As Object, ByVal e As wwTransRowChangeEvent)
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0"),  _
     System.Serializable(),  _
     System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")>  _
    Partial Public Class wwTransDataTable
        Inherits System.Data.DataTable
        Implements System.Collections.IEnumerable
        
        Private columnMaLenh As System.Data.DataColumn
        
        Private columnNgayXuat As System.Data.DataColumn
        
        Private columnSoLenh As System.Data.DataColumn
        
        Private columnMaTichKe As System.Data.DataColumn
        
        Private columnMaDonVi As System.Data.DataColumn
        
        Private columnMaNguon As System.Data.DataColumn
        
        Private columnMaKho As System.Data.DataColumn
        
        Private columnMaVanChuyen As System.Data.DataColumn
        
        Private columnMaPhuongTien As System.Data.DataColumn
        
        Private columnNguoiVanChuyen As System.Data.DataColumn
        
        Private columnMaPhuongThucBan As System.Data.DataColumn
        
        Private columnMaKhachHang As System.Data.DataColumn
        
        Private columnMaNgan As System.Data.DataColumn
        
        Private columnMaHangHoa As System.Data.DataColumn
        
        Private columnDonViTinh As System.Data.DataColumn
        
        Private columnSoLuongDuXuat As System.Data.DataColumn
        
        Private columnSoLuongThucXuat As System.Data.DataColumn
        
        Private columnThoiGianDau As System.Data.DataColumn
        
        Private columnThoiGianCuoi As System.Data.DataColumn
        
        Private columnSl_llkebd As System.Data.DataColumn
        
        Private columnSl_llkekt As System.Data.DataColumn
        
        Private columnHeSo_k As System.Data.DataColumn
        
        Private columnNhietDo As System.Data.DataColumn
        
        Private columnTyTrong_15 As System.Data.DataColumn
        
        Private columnStatus As System.Data.DataColumn
        
        Private columnMaBeXuat As System.Data.DataColumn
        
        Private columnTenHangHoa As System.Data.DataColumn
        
        Private columnThuy As System.Data.DataColumn
        
        Private columnBo As System.Data.DataColumn
        
        Private columnSat As System.Data.DataColumn
        
        Private columnMaCongTo As System.Data.DataColumn
        
        Private columnPR_KEY As System.Data.DataColumn
        
        Private columnLineID As System.Data.DataColumn
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub New()
            MyBase.New
            Me.TableName = "wwTrans"
            Me.BeginInit
            Me.InitClass
            Me.EndInit
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub New(ByVal table As System.Data.DataTable)
            MyBase.New
            Me.TableName = table.TableName
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Sub New(ByVal info As System.Runtime.Serialization.SerializationInfo, ByVal context As System.Runtime.Serialization.StreamingContext)
            MyBase.New(info, context)
            Me.InitVars
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property MaLenhColumn() As System.Data.DataColumn
            Get
                Return Me.columnMaLenh
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property NgayXuatColumn() As System.Data.DataColumn
            Get
                Return Me.columnNgayXuat
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property SoLenhColumn() As System.Data.DataColumn
            Get
                Return Me.columnSoLenh
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property MaTichKeColumn() As System.Data.DataColumn
            Get
                Return Me.columnMaTichKe
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property MaDonViColumn() As System.Data.DataColumn
            Get
                Return Me.columnMaDonVi
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property MaNguonColumn() As System.Data.DataColumn
            Get
                Return Me.columnMaNguon
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property MaKhoColumn() As System.Data.DataColumn
            Get
                Return Me.columnMaKho
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property MaVanChuyenColumn() As System.Data.DataColumn
            Get
                Return Me.columnMaVanChuyen
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property MaPhuongTienColumn() As System.Data.DataColumn
            Get
                Return Me.columnMaPhuongTien
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property NguoiVanChuyenColumn() As System.Data.DataColumn
            Get
                Return Me.columnNguoiVanChuyen
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property MaPhuongThucBanColumn() As System.Data.DataColumn
            Get
                Return Me.columnMaPhuongThucBan
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property MaKhachHangColumn() As System.Data.DataColumn
            Get
                Return Me.columnMaKhachHang
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property MaNganColumn() As System.Data.DataColumn
            Get
                Return Me.columnMaNgan
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property MaHangHoaColumn() As System.Data.DataColumn
            Get
                Return Me.columnMaHangHoa
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property DonViTinhColumn() As System.Data.DataColumn
            Get
                Return Me.columnDonViTinh
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property SoLuongDuXuatColumn() As System.Data.DataColumn
            Get
                Return Me.columnSoLuongDuXuat
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property SoLuongThucXuatColumn() As System.Data.DataColumn
            Get
                Return Me.columnSoLuongThucXuat
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property ThoiGianDauColumn() As System.Data.DataColumn
            Get
                Return Me.columnThoiGianDau
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property ThoiGianCuoiColumn() As System.Data.DataColumn
            Get
                Return Me.columnThoiGianCuoi
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Sl_llkebdColumn() As System.Data.DataColumn
            Get
                Return Me.columnSl_llkebd
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Sl_llkektColumn() As System.Data.DataColumn
            Get
                Return Me.columnSl_llkekt
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property HeSo_kColumn() As System.Data.DataColumn
            Get
                Return Me.columnHeSo_k
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property NhietDoColumn() As System.Data.DataColumn
            Get
                Return Me.columnNhietDo
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property TyTrong_15Column() As System.Data.DataColumn
            Get
                Return Me.columnTyTrong_15
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property StatusColumn() As System.Data.DataColumn
            Get
                Return Me.columnStatus
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property MaBeXuatColumn() As System.Data.DataColumn
            Get
                Return Me.columnMaBeXuat
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property TenHangHoaColumn() As System.Data.DataColumn
            Get
                Return Me.columnTenHangHoa
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property ThuyColumn() As System.Data.DataColumn
            Get
                Return Me.columnThuy
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property BoColumn() As System.Data.DataColumn
            Get
                Return Me.columnBo
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property SatColumn() As System.Data.DataColumn
            Get
                Return Me.columnSat
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property MaCongToColumn() As System.Data.DataColumn
            Get
                Return Me.columnMaCongTo
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property PR_KEYColumn() As System.Data.DataColumn
            Get
                Return Me.columnPR_KEY
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property LineIDColumn() As System.Data.DataColumn
            Get
                Return Me.columnLineID
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count() As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Default ReadOnly Property Item(ByVal index As Integer) As wwTransRow
            Get
                Return CType(Me.Rows(index),wwTransRow)
            End Get
        End Property
        
        Public Event wwTransRowChanging As wwTransRowChangeEventHandler
        
        Public Event wwTransRowChanged As wwTransRowChangeEventHandler
        
        Public Event wwTransRowDeleting As wwTransRowChangeEventHandler
        
        Public Event wwTransRowDeleted As wwTransRowChangeEventHandler
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overloads Sub AddwwTransRow(ByVal row As wwTransRow)
            Me.Rows.Add(row)
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overloads Function AddwwTransRow( _
                    ByVal MaLenh As String,  _
                    ByVal NgayXuat As String,  _
                    ByVal SoLenh As String,  _
                    ByVal MaTichKe As String,  _
                    ByVal MaDonVi As String,  _
                    ByVal MaNguon As String,  _
                    ByVal MaKho As String,  _
                    ByVal MaVanChuyen As String,  _
                    ByVal MaPhuongTien As String,  _
                    ByVal NguoiVanChuyen As String,  _
                    ByVal MaPhuongThucBan As String,  _
                    ByVal MaKhachHang As String,  _
                    ByVal MaNgan As String,  _
                    ByVal MaHangHoa As String,  _
                    ByVal DonViTinh As String,  _
                    ByVal SoLuongDuXuat As String,  _
                    ByVal SoLuongThucXuat As String,  _
                    ByVal ThoiGianDau As String,  _
                    ByVal ThoiGianCuoi As String,  _
                    ByVal Sl_llkebd As String,  _
                    ByVal Sl_llkekt As String,  _
                    ByVal HeSo_k As String,  _
                    ByVal NhietDo As String,  _
                    ByVal TyTrong_15 As String,  _
                    ByVal Status As String,  _
                    ByVal MaBeXuat As String,  _
                    ByVal TenHangHoa As String,  _
                    ByVal Thuy As String,  _
                    ByVal Bo As String,  _
                    ByVal Sat As String,  _
                    ByVal MaCongTo As String,  _
                    ByVal PR_KEY As String,  _
                    ByVal LineID As String) As wwTransRow
            Dim rowwwTransRow As wwTransRow = CType(Me.NewRow,wwTransRow)
            rowwwTransRow.ItemArray = New Object() {MaLenh, NgayXuat, SoLenh, MaTichKe, MaDonVi, MaNguon, MaKho, MaVanChuyen, MaPhuongTien, NguoiVanChuyen, MaPhuongThucBan, MaKhachHang, MaNgan, MaHangHoa, DonViTinh, SoLuongDuXuat, SoLuongThucXuat, ThoiGianDau, ThoiGianCuoi, Sl_llkebd, Sl_llkekt, HeSo_k, NhietDo, TyTrong_15, Status, MaBeXuat, TenHangHoa, Thuy, Bo, Sat, MaCongTo, PR_KEY, LineID}
            Me.Rows.Add(rowwwTransRow)
            Return rowwwTransRow
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overridable Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overrides Function Clone() As System.Data.DataTable
            Dim cln As wwTransDataTable = CType(MyBase.Clone,wwTransDataTable)
            cln.InitVars
            Return cln
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function CreateInstance() As System.Data.DataTable
            Return New wwTransDataTable
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub InitVars()
            Me.columnMaLenh = MyBase.Columns("MaLenh")
            Me.columnNgayXuat = MyBase.Columns("NgayXuat")
            Me.columnSoLenh = MyBase.Columns("SoLenh")
            Me.columnMaTichKe = MyBase.Columns("MaTichKe")
            Me.columnMaDonVi = MyBase.Columns("MaDonVi")
            Me.columnMaNguon = MyBase.Columns("MaNguon")
            Me.columnMaKho = MyBase.Columns("MaKho")
            Me.columnMaVanChuyen = MyBase.Columns("MaVanChuyen")
            Me.columnMaPhuongTien = MyBase.Columns("MaPhuongTien")
            Me.columnNguoiVanChuyen = MyBase.Columns("NguoiVanChuyen")
            Me.columnMaPhuongThucBan = MyBase.Columns("MaPhuongThucBan")
            Me.columnMaKhachHang = MyBase.Columns("MaKhachHang")
            Me.columnMaNgan = MyBase.Columns("MaNgan")
            Me.columnMaHangHoa = MyBase.Columns("MaHangHoa")
            Me.columnDonViTinh = MyBase.Columns("DonViTinh")
            Me.columnSoLuongDuXuat = MyBase.Columns("SoLuongDuXuat")
            Me.columnSoLuongThucXuat = MyBase.Columns("SoLuongThucXuat")
            Me.columnThoiGianDau = MyBase.Columns("ThoiGianDau")
            Me.columnThoiGianCuoi = MyBase.Columns("ThoiGianCuoi")
            Me.columnSl_llkebd = MyBase.Columns("Sl_llkebd")
            Me.columnSl_llkekt = MyBase.Columns("Sl_llkekt")
            Me.columnHeSo_k = MyBase.Columns("HeSo_k")
            Me.columnNhietDo = MyBase.Columns("NhietDo")
            Me.columnTyTrong_15 = MyBase.Columns("TyTrong_15")
            Me.columnStatus = MyBase.Columns("Status")
            Me.columnMaBeXuat = MyBase.Columns("MaBeXuat")
            Me.columnTenHangHoa = MyBase.Columns("TenHangHoa")
            Me.columnThuy = MyBase.Columns("Thuy")
            Me.columnBo = MyBase.Columns("Bo")
            Me.columnSat = MyBase.Columns("Sat")
            Me.columnMaCongTo = MyBase.Columns("MaCongTo")
            Me.columnPR_KEY = MyBase.Columns("PR_KEY")
            Me.columnLineID = MyBase.Columns("LineID")
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Private Sub InitClass()
            Me.columnMaLenh = New System.Data.DataColumn("MaLenh", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnMaLenh)
            Me.columnNgayXuat = New System.Data.DataColumn("NgayXuat", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnNgayXuat)
            Me.columnSoLenh = New System.Data.DataColumn("SoLenh", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnSoLenh)
            Me.columnMaTichKe = New System.Data.DataColumn("MaTichKe", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnMaTichKe)
            Me.columnMaDonVi = New System.Data.DataColumn("MaDonVi", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnMaDonVi)
            Me.columnMaNguon = New System.Data.DataColumn("MaNguon", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnMaNguon)
            Me.columnMaKho = New System.Data.DataColumn("MaKho", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnMaKho)
            Me.columnMaVanChuyen = New System.Data.DataColumn("MaVanChuyen", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnMaVanChuyen)
            Me.columnMaPhuongTien = New System.Data.DataColumn("MaPhuongTien", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnMaPhuongTien)
            Me.columnNguoiVanChuyen = New System.Data.DataColumn("NguoiVanChuyen", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnNguoiVanChuyen)
            Me.columnMaPhuongThucBan = New System.Data.DataColumn("MaPhuongThucBan", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnMaPhuongThucBan)
            Me.columnMaKhachHang = New System.Data.DataColumn("MaKhachHang", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnMaKhachHang)
            Me.columnMaNgan = New System.Data.DataColumn("MaNgan", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnMaNgan)
            Me.columnMaHangHoa = New System.Data.DataColumn("MaHangHoa", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnMaHangHoa)
            Me.columnDonViTinh = New System.Data.DataColumn("DonViTinh", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDonViTinh)
            Me.columnSoLuongDuXuat = New System.Data.DataColumn("SoLuongDuXuat", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnSoLuongDuXuat)
            Me.columnSoLuongThucXuat = New System.Data.DataColumn("SoLuongThucXuat", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnSoLuongThucXuat)
            Me.columnThoiGianDau = New System.Data.DataColumn("ThoiGianDau", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnThoiGianDau)
            Me.columnThoiGianCuoi = New System.Data.DataColumn("ThoiGianCuoi", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnThoiGianCuoi)
            Me.columnSl_llkebd = New System.Data.DataColumn("Sl_llkebd", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnSl_llkebd)
            Me.columnSl_llkekt = New System.Data.DataColumn("Sl_llkekt", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnSl_llkekt)
            Me.columnHeSo_k = New System.Data.DataColumn("HeSo_k", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnHeSo_k)
            Me.columnNhietDo = New System.Data.DataColumn("NhietDo", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnNhietDo)
            Me.columnTyTrong_15 = New System.Data.DataColumn("TyTrong_15", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnTyTrong_15)
            Me.columnStatus = New System.Data.DataColumn("Status", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnStatus)
            Me.columnMaBeXuat = New System.Data.DataColumn("MaBeXuat", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnMaBeXuat)
            Me.columnTenHangHoa = New System.Data.DataColumn("TenHangHoa", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnTenHangHoa)
            Me.columnThuy = New System.Data.DataColumn("Thuy", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnThuy)
            Me.columnBo = New System.Data.DataColumn("Bo", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnBo)
            Me.columnSat = New System.Data.DataColumn("Sat", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnSat)
            Me.columnMaCongTo = New System.Data.DataColumn("MaCongTo", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnMaCongTo)
            Me.columnPR_KEY = New System.Data.DataColumn("PR_KEY", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPR_KEY)
            Me.columnLineID = New System.Data.DataColumn("LineID", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnLineID)
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function NewwwTransRow() As wwTransRow
            Return CType(Me.NewRow,wwTransRow)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function NewRowFromBuilder(ByVal builder As System.Data.DataRowBuilder) As System.Data.DataRow
            Return New wwTransRow(builder)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(wwTransRow)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowChanged(ByVal e As System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.wwTransRowChangedEvent) Is Nothing) Then
                RaiseEvent wwTransRowChanged(Me, New wwTransRowChangeEvent(CType(e.Row,wwTransRow), e.Action))
            End If
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowChanging(ByVal e As System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.wwTransRowChangingEvent) Is Nothing) Then
                RaiseEvent wwTransRowChanging(Me, New wwTransRowChangeEvent(CType(e.Row,wwTransRow), e.Action))
            End If
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowDeleted(ByVal e As System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.wwTransRowDeletedEvent) Is Nothing) Then
                RaiseEvent wwTransRowDeleted(Me, New wwTransRowChangeEvent(CType(e.Row,wwTransRow), e.Action))
            End If
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowDeleting(ByVal e As System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.wwTransRowDeletingEvent) Is Nothing) Then
                RaiseEvent wwTransRowDeleting(Me, New wwTransRowChangeEvent(CType(e.Row,wwTransRow), e.Action))
            End If
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub RemovewwTransRow(ByVal row As wwTransRow)
            Me.Rows.Remove(row)
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Shared Function GetTypedTableSchema(ByVal xs As System.Xml.Schema.XmlSchemaSet) As System.Xml.Schema.XmlSchemaComplexType
            Dim type As System.Xml.Schema.XmlSchemaComplexType = New System.Xml.Schema.XmlSchemaComplexType
            Dim sequence As System.Xml.Schema.XmlSchemaSequence = New System.Xml.Schema.XmlSchemaSequence
            Dim ds As RpDataset = New RpDataset
            xs.Add(ds.GetSchemaSerializable)
            Dim any1 As System.Xml.Schema.XmlSchemaAny = New System.Xml.Schema.XmlSchemaAny
            any1.Namespace = "http://www.w3.org/2001/XMLSchema"
            any1.MinOccurs = New Decimal(0)
            any1.MaxOccurs = Decimal.MaxValue
            any1.ProcessContents = System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any1)
            Dim any2 As System.Xml.Schema.XmlSchemaAny = New System.Xml.Schema.XmlSchemaAny
            any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1"
            any2.MinOccurs = New Decimal(1)
            any2.ProcessContents = System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any2)
            Dim attribute1 As System.Xml.Schema.XmlSchemaAttribute = New System.Xml.Schema.XmlSchemaAttribute
            attribute1.Name = "namespace"
            attribute1.FixedValue = ds.Namespace
            type.Attributes.Add(attribute1)
            Dim attribute2 As System.Xml.Schema.XmlSchemaAttribute = New System.Xml.Schema.XmlSchemaAttribute
            attribute2.Name = "tableTypeName"
            attribute2.FixedValue = "wwTransDataTable"
            type.Attributes.Add(attribute2)
            type.Particle = sequence
            Return type
        End Function
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")>  _
    Partial Public Class wwTransRow
        Inherits System.Data.DataRow
        
        Private tablewwTrans As wwTransDataTable
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub New(ByVal rb As System.Data.DataRowBuilder)
            MyBase.New(rb)
            Me.tablewwTrans = CType(Me.Table,wwTransDataTable)
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property MaLenh() As String
            Get
                Try 
                    Return CType(Me(Me.tablewwTrans.MaLenhColumn),String)
                Catch e As System.InvalidCastException
                    Throw New System.Data.StrongTypingException("The value for column 'MaLenh' in table 'wwTrans' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablewwTrans.MaLenhColumn) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property NgayXuat() As String
            Get
                Try 
                    Return CType(Me(Me.tablewwTrans.NgayXuatColumn),String)
                Catch e As System.InvalidCastException
                    Throw New System.Data.StrongTypingException("The value for column 'NgayXuat' in table 'wwTrans' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablewwTrans.NgayXuatColumn) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SoLenh() As String
            Get
                Try 
                    Return CType(Me(Me.tablewwTrans.SoLenhColumn),String)
                Catch e As System.InvalidCastException
                    Throw New System.Data.StrongTypingException("The value for column 'SoLenh' in table 'wwTrans' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablewwTrans.SoLenhColumn) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property MaTichKe() As String
            Get
                Try 
                    Return CType(Me(Me.tablewwTrans.MaTichKeColumn),String)
                Catch e As System.InvalidCastException
                    Throw New System.Data.StrongTypingException("The value for column 'MaTichKe' in table 'wwTrans' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablewwTrans.MaTichKeColumn) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property MaDonVi() As String
            Get
                Try 
                    Return CType(Me(Me.tablewwTrans.MaDonViColumn),String)
                Catch e As System.InvalidCastException
                    Throw New System.Data.StrongTypingException("The value for column 'MaDonVi' in table 'wwTrans' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablewwTrans.MaDonViColumn) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property MaNguon() As String
            Get
                Try 
                    Return CType(Me(Me.tablewwTrans.MaNguonColumn),String)
                Catch e As System.InvalidCastException
                    Throw New System.Data.StrongTypingException("The value for column 'MaNguon' in table 'wwTrans' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablewwTrans.MaNguonColumn) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property MaKho() As String
            Get
                Try 
                    Return CType(Me(Me.tablewwTrans.MaKhoColumn),String)
                Catch e As System.InvalidCastException
                    Throw New System.Data.StrongTypingException("The value for column 'MaKho' in table 'wwTrans' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablewwTrans.MaKhoColumn) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property MaVanChuyen() As String
            Get
                Try 
                    Return CType(Me(Me.tablewwTrans.MaVanChuyenColumn),String)
                Catch e As System.InvalidCastException
                    Throw New System.Data.StrongTypingException("The value for column 'MaVanChuyen' in table 'wwTrans' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablewwTrans.MaVanChuyenColumn) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property MaPhuongTien() As String
            Get
                Try 
                    Return CType(Me(Me.tablewwTrans.MaPhuongTienColumn),String)
                Catch e As System.InvalidCastException
                    Throw New System.Data.StrongTypingException("The value for column 'MaPhuongTien' in table 'wwTrans' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablewwTrans.MaPhuongTienColumn) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property NguoiVanChuyen() As String
            Get
                Try 
                    Return CType(Me(Me.tablewwTrans.NguoiVanChuyenColumn),String)
                Catch e As System.InvalidCastException
                    Throw New System.Data.StrongTypingException("The value for column 'NguoiVanChuyen' in table 'wwTrans' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablewwTrans.NguoiVanChuyenColumn) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property MaPhuongThucBan() As String
            Get
                Try 
                    Return CType(Me(Me.tablewwTrans.MaPhuongThucBanColumn),String)
                Catch e As System.InvalidCastException
                    Throw New System.Data.StrongTypingException("The value for column 'MaPhuongThucBan' in table 'wwTrans' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablewwTrans.MaPhuongThucBanColumn) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property MaKhachHang() As String
            Get
                Try 
                    Return CType(Me(Me.tablewwTrans.MaKhachHangColumn),String)
                Catch e As System.InvalidCastException
                    Throw New System.Data.StrongTypingException("The value for column 'MaKhachHang' in table 'wwTrans' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablewwTrans.MaKhachHangColumn) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property MaNgan() As String
            Get
                Try 
                    Return CType(Me(Me.tablewwTrans.MaNganColumn),String)
                Catch e As System.InvalidCastException
                    Throw New System.Data.StrongTypingException("The value for column 'MaNgan' in table 'wwTrans' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablewwTrans.MaNganColumn) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property MaHangHoa() As String
            Get
                Try 
                    Return CType(Me(Me.tablewwTrans.MaHangHoaColumn),String)
                Catch e As System.InvalidCastException
                    Throw New System.Data.StrongTypingException("The value for column 'MaHangHoa' in table 'wwTrans' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablewwTrans.MaHangHoaColumn) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DonViTinh() As String
            Get
                Try 
                    Return CType(Me(Me.tablewwTrans.DonViTinhColumn),String)
                Catch e As System.InvalidCastException
                    Throw New System.Data.StrongTypingException("The value for column 'DonViTinh' in table 'wwTrans' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablewwTrans.DonViTinhColumn) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SoLuongDuXuat() As String
            Get
                Try 
                    Return CType(Me(Me.tablewwTrans.SoLuongDuXuatColumn),String)
                Catch e As System.InvalidCastException
                    Throw New System.Data.StrongTypingException("The value for column 'SoLuongDuXuat' in table 'wwTrans' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablewwTrans.SoLuongDuXuatColumn) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SoLuongThucXuat() As String
            Get
                Try 
                    Return CType(Me(Me.tablewwTrans.SoLuongThucXuatColumn),String)
                Catch e As System.InvalidCastException
                    Throw New System.Data.StrongTypingException("The value for column 'SoLuongThucXuat' in table 'wwTrans' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablewwTrans.SoLuongThucXuatColumn) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ThoiGianDau() As String
            Get
                Try 
                    Return CType(Me(Me.tablewwTrans.ThoiGianDauColumn),String)
                Catch e As System.InvalidCastException
                    Throw New System.Data.StrongTypingException("The value for column 'ThoiGianDau' in table 'wwTrans' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablewwTrans.ThoiGianDauColumn) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ThoiGianCuoi() As String
            Get
                Try 
                    Return CType(Me(Me.tablewwTrans.ThoiGianCuoiColumn),String)
                Catch e As System.InvalidCastException
                    Throw New System.Data.StrongTypingException("The value for column 'ThoiGianCuoi' in table 'wwTrans' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablewwTrans.ThoiGianCuoiColumn) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Sl_llkebd() As String
            Get
                Try 
                    Return CType(Me(Me.tablewwTrans.Sl_llkebdColumn),String)
                Catch e As System.InvalidCastException
                    Throw New System.Data.StrongTypingException("The value for column 'Sl_llkebd' in table 'wwTrans' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablewwTrans.Sl_llkebdColumn) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Sl_llkekt() As String
            Get
                Try 
                    Return CType(Me(Me.tablewwTrans.Sl_llkektColumn),String)
                Catch e As System.InvalidCastException
                    Throw New System.Data.StrongTypingException("The value for column 'Sl_llkekt' in table 'wwTrans' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablewwTrans.Sl_llkektColumn) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property HeSo_k() As String
            Get
                Try 
                    Return CType(Me(Me.tablewwTrans.HeSo_kColumn),String)
                Catch e As System.InvalidCastException
                    Throw New System.Data.StrongTypingException("The value for column 'HeSo_k' in table 'wwTrans' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablewwTrans.HeSo_kColumn) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property NhietDo() As String
            Get
                Try 
                    Return CType(Me(Me.tablewwTrans.NhietDoColumn),String)
                Catch e As System.InvalidCastException
                    Throw New System.Data.StrongTypingException("The value for column 'NhietDo' in table 'wwTrans' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablewwTrans.NhietDoColumn) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property TyTrong_15() As String
            Get
                Try 
                    Return CType(Me(Me.tablewwTrans.TyTrong_15Column),String)
                Catch e As System.InvalidCastException
                    Throw New System.Data.StrongTypingException("The value for column 'TyTrong_15' in table 'wwTrans' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablewwTrans.TyTrong_15Column) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Status() As String
            Get
                Try 
                    Return CType(Me(Me.tablewwTrans.StatusColumn),String)
                Catch e As System.InvalidCastException
                    Throw New System.Data.StrongTypingException("The value for column 'Status' in table 'wwTrans' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablewwTrans.StatusColumn) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property MaBeXuat() As String
            Get
                Try 
                    Return CType(Me(Me.tablewwTrans.MaBeXuatColumn),String)
                Catch e As System.InvalidCastException
                    Throw New System.Data.StrongTypingException("The value for column 'MaBeXuat' in table 'wwTrans' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablewwTrans.MaBeXuatColumn) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property TenHangHoa() As String
            Get
                Try 
                    Return CType(Me(Me.tablewwTrans.TenHangHoaColumn),String)
                Catch e As System.InvalidCastException
                    Throw New System.Data.StrongTypingException("The value for column 'TenHangHoa' in table 'wwTrans' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablewwTrans.TenHangHoaColumn) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Thuy() As String
            Get
                Try 
                    Return CType(Me(Me.tablewwTrans.ThuyColumn),String)
                Catch e As System.InvalidCastException
                    Throw New System.Data.StrongTypingException("The value for column 'Thuy' in table 'wwTrans' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablewwTrans.ThuyColumn) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Bo() As String
            Get
                Try 
                    Return CType(Me(Me.tablewwTrans.BoColumn),String)
                Catch e As System.InvalidCastException
                    Throw New System.Data.StrongTypingException("The value for column 'Bo' in table 'wwTrans' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablewwTrans.BoColumn) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Sat() As String
            Get
                Try 
                    Return CType(Me(Me.tablewwTrans.SatColumn),String)
                Catch e As System.InvalidCastException
                    Throw New System.Data.StrongTypingException("The value for column 'Sat' in table 'wwTrans' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablewwTrans.SatColumn) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property MaCongTo() As String
            Get
                Try 
                    Return CType(Me(Me.tablewwTrans.MaCongToColumn),String)
                Catch e As System.InvalidCastException
                    Throw New System.Data.StrongTypingException("The value for column 'MaCongTo' in table 'wwTrans' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablewwTrans.MaCongToColumn) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property PR_KEY() As String
            Get
                Try 
                    Return CType(Me(Me.tablewwTrans.PR_KEYColumn),String)
                Catch e As System.InvalidCastException
                    Throw New System.Data.StrongTypingException("The value for column 'PR_KEY' in table 'wwTrans' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablewwTrans.PR_KEYColumn) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property LineID() As String
            Get
                Try 
                    Return CType(Me(Me.tablewwTrans.LineIDColumn),String)
                Catch e As System.InvalidCastException
                    Throw New System.Data.StrongTypingException("The value for column 'LineID' in table 'wwTrans' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablewwTrans.LineIDColumn) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsMaLenhNull() As Boolean
            Return Me.IsNull(Me.tablewwTrans.MaLenhColumn)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetMaLenhNull()
            Me(Me.tablewwTrans.MaLenhColumn) = System.Convert.DBNull
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsNgayXuatNull() As Boolean
            Return Me.IsNull(Me.tablewwTrans.NgayXuatColumn)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetNgayXuatNull()
            Me(Me.tablewwTrans.NgayXuatColumn) = System.Convert.DBNull
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsSoLenhNull() As Boolean
            Return Me.IsNull(Me.tablewwTrans.SoLenhColumn)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetSoLenhNull()
            Me(Me.tablewwTrans.SoLenhColumn) = System.Convert.DBNull
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsMaTichKeNull() As Boolean
            Return Me.IsNull(Me.tablewwTrans.MaTichKeColumn)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetMaTichKeNull()
            Me(Me.tablewwTrans.MaTichKeColumn) = System.Convert.DBNull
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsMaDonViNull() As Boolean
            Return Me.IsNull(Me.tablewwTrans.MaDonViColumn)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetMaDonViNull()
            Me(Me.tablewwTrans.MaDonViColumn) = System.Convert.DBNull
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsMaNguonNull() As Boolean
            Return Me.IsNull(Me.tablewwTrans.MaNguonColumn)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetMaNguonNull()
            Me(Me.tablewwTrans.MaNguonColumn) = System.Convert.DBNull
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsMaKhoNull() As Boolean
            Return Me.IsNull(Me.tablewwTrans.MaKhoColumn)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetMaKhoNull()
            Me(Me.tablewwTrans.MaKhoColumn) = System.Convert.DBNull
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsMaVanChuyenNull() As Boolean
            Return Me.IsNull(Me.tablewwTrans.MaVanChuyenColumn)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetMaVanChuyenNull()
            Me(Me.tablewwTrans.MaVanChuyenColumn) = System.Convert.DBNull
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsMaPhuongTienNull() As Boolean
            Return Me.IsNull(Me.tablewwTrans.MaPhuongTienColumn)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetMaPhuongTienNull()
            Me(Me.tablewwTrans.MaPhuongTienColumn) = System.Convert.DBNull
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsNguoiVanChuyenNull() As Boolean
            Return Me.IsNull(Me.tablewwTrans.NguoiVanChuyenColumn)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetNguoiVanChuyenNull()
            Me(Me.tablewwTrans.NguoiVanChuyenColumn) = System.Convert.DBNull
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsMaPhuongThucBanNull() As Boolean
            Return Me.IsNull(Me.tablewwTrans.MaPhuongThucBanColumn)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetMaPhuongThucBanNull()
            Me(Me.tablewwTrans.MaPhuongThucBanColumn) = System.Convert.DBNull
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsMaKhachHangNull() As Boolean
            Return Me.IsNull(Me.tablewwTrans.MaKhachHangColumn)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetMaKhachHangNull()
            Me(Me.tablewwTrans.MaKhachHangColumn) = System.Convert.DBNull
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsMaNganNull() As Boolean
            Return Me.IsNull(Me.tablewwTrans.MaNganColumn)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetMaNganNull()
            Me(Me.tablewwTrans.MaNganColumn) = System.Convert.DBNull
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsMaHangHoaNull() As Boolean
            Return Me.IsNull(Me.tablewwTrans.MaHangHoaColumn)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetMaHangHoaNull()
            Me(Me.tablewwTrans.MaHangHoaColumn) = System.Convert.DBNull
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsDonViTinhNull() As Boolean
            Return Me.IsNull(Me.tablewwTrans.DonViTinhColumn)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetDonViTinhNull()
            Me(Me.tablewwTrans.DonViTinhColumn) = System.Convert.DBNull
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsSoLuongDuXuatNull() As Boolean
            Return Me.IsNull(Me.tablewwTrans.SoLuongDuXuatColumn)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetSoLuongDuXuatNull()
            Me(Me.tablewwTrans.SoLuongDuXuatColumn) = System.Convert.DBNull
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsSoLuongThucXuatNull() As Boolean
            Return Me.IsNull(Me.tablewwTrans.SoLuongThucXuatColumn)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetSoLuongThucXuatNull()
            Me(Me.tablewwTrans.SoLuongThucXuatColumn) = System.Convert.DBNull
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsThoiGianDauNull() As Boolean
            Return Me.IsNull(Me.tablewwTrans.ThoiGianDauColumn)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetThoiGianDauNull()
            Me(Me.tablewwTrans.ThoiGianDauColumn) = System.Convert.DBNull
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsThoiGianCuoiNull() As Boolean
            Return Me.IsNull(Me.tablewwTrans.ThoiGianCuoiColumn)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetThoiGianCuoiNull()
            Me(Me.tablewwTrans.ThoiGianCuoiColumn) = System.Convert.DBNull
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsSl_llkebdNull() As Boolean
            Return Me.IsNull(Me.tablewwTrans.Sl_llkebdColumn)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetSl_llkebdNull()
            Me(Me.tablewwTrans.Sl_llkebdColumn) = System.Convert.DBNull
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsSl_llkektNull() As Boolean
            Return Me.IsNull(Me.tablewwTrans.Sl_llkektColumn)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetSl_llkektNull()
            Me(Me.tablewwTrans.Sl_llkektColumn) = System.Convert.DBNull
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsHeSo_kNull() As Boolean
            Return Me.IsNull(Me.tablewwTrans.HeSo_kColumn)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetHeSo_kNull()
            Me(Me.tablewwTrans.HeSo_kColumn) = System.Convert.DBNull
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsNhietDoNull() As Boolean
            Return Me.IsNull(Me.tablewwTrans.NhietDoColumn)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetNhietDoNull()
            Me(Me.tablewwTrans.NhietDoColumn) = System.Convert.DBNull
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsTyTrong_15Null() As Boolean
            Return Me.IsNull(Me.tablewwTrans.TyTrong_15Column)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetTyTrong_15Null()
            Me(Me.tablewwTrans.TyTrong_15Column) = System.Convert.DBNull
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsStatusNull() As Boolean
            Return Me.IsNull(Me.tablewwTrans.StatusColumn)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetStatusNull()
            Me(Me.tablewwTrans.StatusColumn) = System.Convert.DBNull
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsMaBeXuatNull() As Boolean
            Return Me.IsNull(Me.tablewwTrans.MaBeXuatColumn)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetMaBeXuatNull()
            Me(Me.tablewwTrans.MaBeXuatColumn) = System.Convert.DBNull
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsTenHangHoaNull() As Boolean
            Return Me.IsNull(Me.tablewwTrans.TenHangHoaColumn)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetTenHangHoaNull()
            Me(Me.tablewwTrans.TenHangHoaColumn) = System.Convert.DBNull
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsThuyNull() As Boolean
            Return Me.IsNull(Me.tablewwTrans.ThuyColumn)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetThuyNull()
            Me(Me.tablewwTrans.ThuyColumn) = System.Convert.DBNull
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsBoNull() As Boolean
            Return Me.IsNull(Me.tablewwTrans.BoColumn)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetBoNull()
            Me(Me.tablewwTrans.BoColumn) = System.Convert.DBNull
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsSatNull() As Boolean
            Return Me.IsNull(Me.tablewwTrans.SatColumn)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetSatNull()
            Me(Me.tablewwTrans.SatColumn) = System.Convert.DBNull
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsMaCongToNull() As Boolean
            Return Me.IsNull(Me.tablewwTrans.MaCongToColumn)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetMaCongToNull()
            Me(Me.tablewwTrans.MaCongToColumn) = System.Convert.DBNull
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsPR_KEYNull() As Boolean
            Return Me.IsNull(Me.tablewwTrans.PR_KEYColumn)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetPR_KEYNull()
            Me(Me.tablewwTrans.PR_KEYColumn) = System.Convert.DBNull
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsLineIDNull() As Boolean
            Return Me.IsNull(Me.tablewwTrans.LineIDColumn)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetLineIDNull()
            Me(Me.tablewwTrans.LineIDColumn) = System.Convert.DBNull
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")>  _
    Public Class wwTransRowChangeEvent
        Inherits System.EventArgs
        
        Private eventRow As wwTransRow
        
        Private eventAction As System.Data.DataRowAction
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub New(ByVal row As wwTransRow, ByVal action As System.Data.DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Row() As wwTransRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Action() As System.Data.DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
