
CREATE TABLE [dbo].[ztbl53C](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[HeSo] [numeric](18, 8) NULL,
	[NhietDo] [numeric](6, 2) NULL,
	[VCF] [numeric](10, 4) NULL,
 CONSTRAINT [PK_ztbl53C] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

