alter table tblTank add  Map_Sap1 nvarchar(100)
alter table tblTank add  Map_Sap nvarchar(100)
alter table tblconfig add  Plant_DB nvarchar(50)
alter table [dbo].[ztblTankLineImp] add [WaterHeight]  decimal(18,4)
alter table [ztblTankLineImp] add BAREM_HEIGHT nvarchar(10), BAREM_WATER nvarchar(10)