

CREATE TABLE [dbo].[tblLenhXuatChiTietE5_Hist](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[MaNgan] [nvarchar](3) NOT NULL,
	[MaLenh] [nvarchar](4) NOT NULL,
	[NgayXuat] [datetime] NOT NULL,
	[LineID] [nvarchar](6) NOT NULL,
	[SoLuongDuXuat] [decimal](18, 2) NULL,
	[SoLuongThucXuat] [decimal](18, 2) NULL,
	[ThoiGianDau] [datetime] NULL,
	[ThoiGianCuoi] [datetime] NULL,
	[Sl_llkebd] [decimal](18, 2) NULL,
	[Sl_llkekt] [decimal](18, 2) NULL,
	[HeSo_k] [decimal](6, 4) NULL,
	[NhietDo] [decimal](5, 2) NULL,
	[TyTrong_15] [decimal](6, 4) NULL,
	[MaDanXuat] [nvarchar](2) NULL,
	[MaLoi] [nvarchar](6) NULL,
	[TrangThai] [nvarchar](20) NULL,
	[MaLuuLuongKe] [nvarchar](30) NULL,
	[MaEntry] [decimal](6, 0) NULL,
	[MaLo] [decimal](6, 0) NULL,
	[GhiChu] [nvarchar](50) NULL,
	[Status] [char](2) NULL,
	[ERate] [nvarchar](6) NULL,
	[GV] [real] NULL,
	[GST] [real] NULL,
	[GVTOTAL_START] [real] NULL,
	[GVTOTAL_END] [real] NULL,
	[GSTTOTAL_START] [real] NULL,
	[GSTTOTAL_END] [real] NULL,
	[KF] [real] NULL,
	[KF_E] [real] NULL,
	[TY_TRONG] [real] NULL,
	[AVG_MF] [real] NULL,
	[AVG_MF_E] [real] NULL,
	[AVG_CTL] [real] NULL,
	[AVG_CTL_E] [real] NULL,
	[AVG_CTL_BASE] [real] NULL,
	[RTD_OFFSET] [real] NULL,
	[GV_E] [real] NULL,
	[GST_E] [real] NULL,
	[GVTOTAL_E_START] [real] NULL,
	[GVTOTAL_E_END] [real] NULL,
	[GSTTOTAL_E_START] [real] NULL,
	[GSTTOTAL_E_END] [real] NULL,
	[GV_BASE] [real] NULL,
	[GST_BASE] [real] NULL,
	[GVTOTAL_BASE_START] [real] NULL,
	[GVTOTAL_BASE_END] [real] NULL,
	[GSTTOTAL_BASE_START] [real] NULL,
	[GSTTOTAL_BASE_END] [real] NULL,
	[TYLE_TTE] [real] NULL,
	[V_PRESET] [real] NULL,
	[TYLE_PRESET] [real] NULL,
	[TYTRONG_BASE] [real] NULL,
	[TYTRONG_E] [real] NULL,
	[NGAY_DKY] [datetime] NULL,
	[NGAY_BD] [datetime] NULL,
	[NGAY_KT] [datetime] NULL,
	[SO_CTU] [char](7) NULL,
	[MA_LENH] [numeric](10, 0) NULL,
	[CARD_DATA] [char](7) NULL,
	[MA_NGAN] [tinyint] NULL,
	[MA_HHOA] [char](7) NULL,
	[MA_HONG] [tinyint] NULL,
	[MA_KHO] [char](8) NULL,
	[NHIET_DOTB] [real] NULL,
	[TRANG_THAI] [int] NULL,
	[SO_PTIEN] [char](10) NULL,
	[LAI_XE] [char](20) NULL,
	[TY_TRONGTB] [real] NULL,
	[TY_TRONGTB_BASE] [real] NULL,
	[TY_TRONGTB_E] [real] NULL,
	[MASS] [real] NULL,
	[MASS_BASE] [real] NULL,
	[MASS_E] [real] NULL,
	[MASSTOTAL_START] [real] NULL,
	[MASSTOTAL_END] [real] NULL,
	[MASSTOTAL_BASE_START] [real] NULL,
	[MASSTOTAL_BASE_END] [real] NULL,
	[MASSTOTAL_E_START] [real] NULL,
	[MASSTOTAL_E_END] [real] NULL,
	[Createby] [nvarchar](30) NULL,
	[UpdatedBy] [nvarchar](30) NULL,
	[CreateDate] [datetime] NULL,
	[UpdateDate] [datetime] NULL,
	[DungTichNgan] [int] NULL,
	[TableID] [varchar](8) NULL,
	[MaTuDongHoa] [varchar](8) NULL,
	[Row_id] [int]   NULL,
	[PhuongTien] [nvarchar](50) NULL,
	[Record_Status] [nvarchar](50) NULL,
	[SO_TT] [int] NULL,
	[FlagTankLine] [nvarchar](1) NULL,
	[GST_TDH] [decimal](18, 2) NULL, cStatus varchar(1)) 
