
CREATE TABLE [dbo].[tblLenhXuat_HangHoaE5_Hist](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[LineID] [nvarchar](6) NOT NULL,
	[MaLenh] [nvarchar](4) NOT NULL,
	[NgayXuat] [datetime] NOT NULL,
	[SoLenh] [nvarchar](10) NULL,
	[TongXuat] [decimal](18, 2) NULL,
	[TongDuXuat] [decimal](18, 2) NULL,
	[MaHangHoa] [nvarchar](18) NOT NULL,
	[DonViTinh] [nvarchar](3) NULL,
	[BeXuat] [nvarchar](20) NULL,
	[TableID] [nvarchar](8) NOT NULL,
	[MeterId] [char](4) NULL,
	[Createby] [nvarchar](30) NULL,
	[UpdatedBy] [nvarchar](30) NULL,
	[CreateDate] [datetime] NULL,
	[UpdateDate] [datetime] NULL,
	[QCI_KG] [decimal](18, 2) NULL,
	[QCI_NhietDo] [decimal](5, 2) NULL,
	[QCI_TyTrong] [decimal](10, 4) NULL,
	[DonGia] [decimal](18, 6) NULL,
	[CurrencyKey] [varchar](5) NULL,
	[VCF] [decimal](6, 4) NULL,
	[WCF] [decimal](6, 4) NULL,
	[NhietDo_BQGQ] [decimal](6, 4) NULL,
	[D15_BQGQ] [decimal](6, 4) NULL,
	[KG] [decimal](18, 2) NULL,
	[L15] [decimal](18, 2) NULL,
	[GiaCty] [decimal](18, 6) NULL,
	[PhiVT] [decimal](18, 6) NULL,
	[TheBVMT] [decimal](18, 6) NULL
	, cStatus varchar(1))

